### PR TITLE
Readme wiki

### PR DESCRIPTION
**Pull request by Ramin-Farhadi**
Readme was modified

### CODE REVIEW

**Review by kimberspencer — COMMENTED** [review]
Initial feedback. Will probably have more once I test the slider.

* Installation section: add links to "plugin zip file" and "ACF Pro" so that people don't have to look for them.
* Usage section: 
    - Should we address use cases? When to use and not to use this functionality? 
    - Is the first "Creating Sliders" meant to be a heading? 
    - I'd recommend using an ordered list for the Creating Sliders steps.
    - Looks like the "Displaying Sliders" heading isn't properly formatted, so it's grouped into the steps in the previous "Creating Sliders" section. 
    - Can you use the title of the slider instead of the slug or post-id? 
* UI Behavior section: I'd recommend an unordered list to help with readability.

**Review by jmbarne3 — APPROVED** [review]
Contingent on Kim's suggestions being integrated into the wiki, this look good.

Since changes to the wiki don't show up in these pull requests, please make sure to note in comments when changes have been made, or reasons they shouldn't be made. This space is for discussion, and it's good to have the discussion right here in the pull request, as it created a record to refer back to. We can use it to remind ourselves why something is a certain way when we've completely forgotten why we did a certain thing years from now.

**Comment by Ramin-Farhadi** [comment]
@kimberspencer Please review the wiki section again. I made some changes including adding some screen shots.

**Review by kimberspencer — APPROVED** [review]
Periods are missing at the end of some sentences. I like the use of visuals. Remove "Welcome to the ucf-vertical-slide-plugin wiki!" at the very end. Looking good!

**Pull request merged**
